# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/" # Location of workflow files
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "UTC"
    labels: ["dependencies", "ci"]
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      actions-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  # Keep Python dependencies up to date (parsed from pyproject/requirements where applicable)
  - package-ecosystem: "pip"
    directory: "/" # Project root containing pyproject.toml
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "UTC"
    labels: ["dependencies", "python"]
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    groups:
      python-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]

