# Pre-commit configuration for Syntrix-Base
# Install locally:
#   pip install pre-commit ruff
#   pre-commit install
# Run on all files:
#   pre-commit run --all-files

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
      - id: ruff-format
