blank_issues_enabled: false
contact_links:
  - name: Security Reports
    url: https://github.com/paredezadrian/syntrix-base/security/advisories/new
    about: Please report security vulnerabilities privately via GitHub Security Advisories.

